
package com.raven.main;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Huynh Ai Quoc
 */
public class LoadingScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoadingScreen
     */
    public LoadingScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        LoadingText = new javax.swing.JLabel();
        Tittle = new javax.swing.JLabel();
        Percent = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoadingText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoadingText.setForeground(new java.awt.Color(255, 255, 255));
        LoadingText.setText("Loading...");
        jPanel3.add(LoadingText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 300, -1));

        Tittle.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        Tittle.setForeground(new java.awt.Color(255, 255, 255));
        Tittle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/logo.png"))); // NOI18N
        Tittle.setText("Nong Lam Application");
        jPanel3.add(Tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 460, -1));

        Percent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Percent.setForeground(new java.awt.Color(255, 255, 255));
        Percent.setText("0 %");
        jPanel3.add(Percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 50, 20));
        jPanel3.add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 501, 730, 20));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/f5dee9eb82760a37400cf4b221d3d774.gif"))); // NOI18N
        BackgroundImage.setText("jLabel2");
        jPanel3.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        LoadingScreen ls = new LoadingScreen();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ls.setVisible(true);
            }
        });

        Main main = new Main();

        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(100);
                ls.ProgressBar.setValue(i);
                ls.Percent.setText(String.valueOf(i) + "%");

                if(i == 10){
                    ls.LoadingText.setText("Turning On Modules...");
                }
                if(i == 20){
                    ls.LoadingText.setText("Loading Modules...");
                }
                if(i == 30){
                    ls.LoadingText.setText("Waiting...!");
                }
                if(i == 50){
                    ls.LoadingText.setText("Connecting to Database...");
                }
                if(i == 70){
                    ls.LoadingText.setText("Connection Successfull !");
                }
                if(i == 80){
                    ls.LoadingText.setText("Launching Application...");
                }
                if (i == 100) {
                    ls.setVisible(false);
                    ls.dispose();
                }
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(LoadingScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        main.setVisible(true);
        ls.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JLabel LoadingText;
    private javax.swing.JLabel Percent;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel Tittle;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
